image: gelin/geberdur.ru-pipeline
pipelines:
  default:
    - step:
        script:
          - make build
          - (umask  077 ; echo $DEPLOY_SSH_KEY | base64 --decode > ~/.ssh/id_rsa)
          - make deploy
